-- PROCEDIMIENTO ALMACENADO, PARA INSERTAR NUEVO ARTICULO
DROP PROCEDURE IF EXISTS SP_INSERTAR_ARTICULO;
DELIMITER //
CREATE PROCEDURE SP_INSERTAR_ARTICULO(
	IN P_ID_ESTADO_ARTICULO INT(11),
	IN P_ID_PERSONA_USUARIO_REGISTRA INT(11),
	IN P_ID_CATEGORIA_ARTICULOS INT(11),
	IN P_ID_UBICACION_ARTICULO INT(11),
	IN P_NOMBRE_ARTICULO VARCHAR(45),
	IN P_PRECIO_ARTICULO FLOAT(20),
	IN P_CANTIDAD INT(11),
	IN P_FECHA_REGISTRO_ART DATE,
	IN P_DESCRIPCION_ARTICULO VARCHAR(500)
)
BEGIN
	INSERT INTO TBL_ARTICULOS(
		ID_ESTADO_ARTICULO,
		ID_PERSONA_USUARIO_REGISTRA,
		ID_CATEGORIA_ARTICULOS,
		ID_UBICACION_ARTICULO,
		NOMBRE_ARTICULO,
		PRECIO_ARTICULO,
		CANTIDAD,
		FECHA_REGISTRO_ART,
		DESCRIPCION_ARTICULO)
	VALUES(P_ID_ESTADO_ARTICULO,
		P_ID_PERSONA_USUARIO_REGISTRA,
		P_ID_CATEGORIA_ARTICULOS,
		P_ID_UBICACION_ARTICULO,
		P_NOMBRE_ARTICULO,
		P_PRECIO_ARTICULO,
		P_CANTIDAD,
		P_FECHA_REGISTRO_ART,
		P_DESCRIPCION_ARTICULO);
END //
DELIMITER //;

-- PROCEDIMIENTO ALMACENADO PARA ACTUALIZAR ARTICULO
DROP PROCEDURE IF EXISTS SP_ACTUALIZAR_ARTICULO;
DELIMITER //
CREATE PROCEDURE SP_ACTUALIZAR_ARTICULO(
  IN P_ID_ARTICULOS INT(11),
  IN P_ID_ESTADO_ARTICULO INT(11),
  IN P_ID_CATEGORIA_ARTICULOS INT(11),
  IN P_ID_UBICACION_ARTICULO INT(11),
  IN P_NOMBRE_ARTICULO VARCHAR(45),
  IN P_PRECIO_ARTICULO FLOAT(20),
  IN P_CANTIDAD INT(11),
  IN P_DESCRIPCION_ARTICULO VARCHAR(500)
)
BEGIN
  UPDATE TBL_ARTICULOS
  SET
    ID_ESTADO_ARTICULO = P_ID_ESTADO_ARTICULO,
    ID_CATEGORIA_ARTICULOS = P_ID_CATEGORIA_ARTICULOS,
    ID_UBICACION_ARTICULO = P_ID_UBICACION_ARTICULOS,
    NOMBRE_ARTICULO = P_NOMBRE_ARTICULO, 
    DESCRIPCION_ARTICULO = P_DESCRIPCION_ARTICULO, 
    PRECIO_ARTICULO = P_PRECIO_ARTICULO, 
    CANTIDAD = P_CANTIDAD 
  WHERE ID_ARTICULOS= P_ID_ARTICULOS;  
END //
DELIMITER // 

